version: '2'
services:
  web:
    build: app
    volumes:
      - "./app/app.js:/src/app.js"
      - "./app/index.js:/src/index.js"
      - "./app/routes:/src/routes"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
  gitlab:
    image: gitlab/gitlab-ce